/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as InstructorRouteImport } from './routes/instructor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as InstructorsInstructorIdRouteImport } from './routes/instructors.$instructorId'
import { Route as InstructorStudentsRouteImport } from './routes/instructor.students'
import { Route as InstructorEarningsRouteImport } from './routes/instructor.earnings'
import { Route as InstructorCoursesRouteImport } from './routes/instructor.courses'
import { Route as InstructorApplyRouteImport } from './routes/instructor.apply'
import { Route as InstructorAnnouncementsRouteImport } from './routes/instructor.announcements'
import { Route as InstructorAnalyticsRouteImport } from './routes/instructor.analytics'
import { Route as EnrollCourseIdRouteImport } from './routes/enroll.$courseId'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as InstructorCoursesCourseIdRouteImport } from './routes/instructor.courses.$courseId'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorsInstructorIdRoute = InstructorsInstructorIdRouteImport.update({
  id: '/instructors/$instructorId',
  path: '/instructors/$instructorId',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorStudentsRoute = InstructorStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorEarningsRoute = InstructorEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorCoursesRoute = InstructorCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorApplyRoute = InstructorApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorAnnouncementsRoute = InstructorAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorAnalyticsRoute = InstructorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => InstructorRoute,
} as any)
const EnrollCourseIdRoute = EnrollCourseIdRouteImport.update({
  id: '/enroll/$courseId',
  path: '/enroll/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorCoursesCourseIdRoute =
  InstructorCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => InstructorCoursesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/instructor': typeof InstructorRouteWithChildren
  '/purchases': typeof PurchasesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/wishlist': typeof WishlistRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/enroll/$courseId': typeof EnrollCourseIdRoute
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/announcements': typeof InstructorAnnouncementsRoute
  '/instructor/apply': typeof InstructorApplyRoute
  '/instructor/courses': typeof InstructorCoursesRouteWithChildren
  '/instructor/earnings': typeof InstructorEarningsRoute
  '/instructor/students': typeof InstructorStudentsRoute
  '/instructors/$instructorId': typeof InstructorsInstructorIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/instructor/courses/$courseId': typeof InstructorCoursesCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/instructor': typeof InstructorRouteWithChildren
  '/purchases': typeof PurchasesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/wishlist': typeof WishlistRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/enroll/$courseId': typeof EnrollCourseIdRoute
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/announcements': typeof InstructorAnnouncementsRoute
  '/instructor/apply': typeof InstructorApplyRoute
  '/instructor/courses': typeof InstructorCoursesRouteWithChildren
  '/instructor/earnings': typeof InstructorEarningsRoute
  '/instructor/students': typeof InstructorStudentsRoute
  '/instructors/$instructorId': typeof InstructorsInstructorIdRoute
  '/courses': typeof CoursesIndexRoute
  '/instructor/courses/$courseId': typeof InstructorCoursesCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/instructor': typeof InstructorRouteWithChildren
  '/purchases': typeof PurchasesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/wishlist': typeof WishlistRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/enroll/$courseId': typeof EnrollCourseIdRoute
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/announcements': typeof InstructorAnnouncementsRoute
  '/instructor/apply': typeof InstructorApplyRoute
  '/instructor/courses': typeof InstructorCoursesRouteWithChildren
  '/instructor/earnings': typeof InstructorEarningsRoute
  '/instructor/students': typeof InstructorStudentsRoute
  '/instructors/$instructorId': typeof InstructorsInstructorIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/instructor/courses/$courseId': typeof InstructorCoursesCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/dashboard'
    | '/instructor'
    | '/purchases'
    | '/reset-password'
    | '/reviews'
    | '/wishlist'
    | '/courses/$courseId'
    | '/enroll/$courseId'
    | '/instructor/analytics'
    | '/instructor/announcements'
    | '/instructor/apply'
    | '/instructor/courses'
    | '/instructor/earnings'
    | '/instructor/students'
    | '/instructors/$instructorId'
    | '/courses/'
    | '/instructor/courses/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/dashboard'
    | '/instructor'
    | '/purchases'
    | '/reset-password'
    | '/reviews'
    | '/wishlist'
    | '/courses/$courseId'
    | '/enroll/$courseId'
    | '/instructor/analytics'
    | '/instructor/announcements'
    | '/instructor/apply'
    | '/instructor/courses'
    | '/instructor/earnings'
    | '/instructor/students'
    | '/instructors/$instructorId'
    | '/courses'
    | '/instructor/courses/$courseId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/dashboard'
    | '/instructor'
    | '/purchases'
    | '/reset-password'
    | '/reviews'
    | '/wishlist'
    | '/courses/$courseId'
    | '/enroll/$courseId'
    | '/instructor/analytics'
    | '/instructor/announcements'
    | '/instructor/apply'
    | '/instructor/courses'
    | '/instructor/earnings'
    | '/instructor/students'
    | '/instructors/$instructorId'
    | '/courses/'
    | '/instructor/courses/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  InstructorRoute: typeof InstructorRouteWithChildren
  PurchasesRoute: typeof PurchasesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewsRoute: typeof ReviewsRoute
  WishlistRoute: typeof WishlistRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  EnrollCourseIdRoute: typeof EnrollCourseIdRoute
  InstructorsInstructorIdRoute: typeof InstructorsInstructorIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructors/$instructorId': {
      id: '/instructors/$instructorId'
      path: '/instructors/$instructorId'
      fullPath: '/instructors/$instructorId'
      preLoaderRoute: typeof InstructorsInstructorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/students': {
      id: '/instructor/students'
      path: '/students'
      fullPath: '/instructor/students'
      preLoaderRoute: typeof InstructorStudentsRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/earnings': {
      id: '/instructor/earnings'
      path: '/earnings'
      fullPath: '/instructor/earnings'
      preLoaderRoute: typeof InstructorEarningsRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/courses': {
      id: '/instructor/courses'
      path: '/courses'
      fullPath: '/instructor/courses'
      preLoaderRoute: typeof InstructorCoursesRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/apply': {
      id: '/instructor/apply'
      path: '/apply'
      fullPath: '/instructor/apply'
      preLoaderRoute: typeof InstructorApplyRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/announcements': {
      id: '/instructor/announcements'
      path: '/announcements'
      fullPath: '/instructor/announcements'
      preLoaderRoute: typeof InstructorAnnouncementsRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/analytics': {
      id: '/instructor/analytics'
      path: '/analytics'
      fullPath: '/instructor/analytics'
      preLoaderRoute: typeof InstructorAnalyticsRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/enroll/$courseId': {
      id: '/enroll/$courseId'
      path: '/enroll/$courseId'
      fullPath: '/enroll/$courseId'
      preLoaderRoute: typeof EnrollCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/courses/$courseId': {
      id: '/instructor/courses/$courseId'
      path: '/$courseId'
      fullPath: '/instructor/courses/$courseId'
      preLoaderRoute: typeof InstructorCoursesCourseIdRouteImport
      parentRoute: typeof InstructorCoursesRoute
    }
  }
}

interface InstructorCoursesRouteChildren {
  InstructorCoursesCourseIdRoute: typeof InstructorCoursesCourseIdRoute
}

const InstructorCoursesRouteChildren: InstructorCoursesRouteChildren = {
  InstructorCoursesCourseIdRoute: InstructorCoursesCourseIdRoute,
}

const InstructorCoursesRouteWithChildren =
  InstructorCoursesRoute._addFileChildren(InstructorCoursesRouteChildren)

interface InstructorRouteChildren {
  InstructorAnalyticsRoute: typeof InstructorAnalyticsRoute
  InstructorAnnouncementsRoute: typeof InstructorAnnouncementsRoute
  InstructorApplyRoute: typeof InstructorApplyRoute
  InstructorCoursesRoute: typeof InstructorCoursesRouteWithChildren
  InstructorEarningsRoute: typeof InstructorEarningsRoute
  InstructorStudentsRoute: typeof InstructorStudentsRoute
}

const InstructorRouteChildren: InstructorRouteChildren = {
  InstructorAnalyticsRoute: InstructorAnalyticsRoute,
  InstructorAnnouncementsRoute: InstructorAnnouncementsRoute,
  InstructorApplyRoute: InstructorApplyRoute,
  InstructorCoursesRoute: InstructorCoursesRouteWithChildren,
  InstructorEarningsRoute: InstructorEarningsRoute,
  InstructorStudentsRoute: InstructorStudentsRoute,
}

const InstructorRouteWithChildren = InstructorRoute._addFileChildren(
  InstructorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  InstructorRoute: InstructorRouteWithChildren,
  PurchasesRoute: PurchasesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewsRoute: ReviewsRoute,
  WishlistRoute: WishlistRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  EnrollCourseIdRoute: EnrollCourseIdRoute,
  InstructorsInstructorIdRoute: InstructorsInstructorIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
